name: CI/CD
on:
    push:
    pull_request:
jobs:
    #test:
    #strategy:
    #matrix:
    #os: [ubuntu-latest]
    #runs-on: ${{ matrix.os }}

    #steps:
    #- uses: actions/checkout@v4
    #- uses: cachix/install-nix-action@v26
    #- uses: cachix/cachix-action@v14
    #with:
    #name: devenv
    #- name: Install devenv.sh
    #run: nix profile install nixpkgs#devenv

    #- name: Build the devenv shell and run any pre-commit hooks
    #run: devenv test

    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        # Only if pushed tags
        if: startsWith(github.ref, 'refs/tags/v')
        permissions:
            # Required to create a release
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v26
            - uses: cachix/cachix-action@v14
              with:
                  name: devenv
            - name: Install devenv.sh
              run: nix profile install nixpkgs#devenv

            - name: Build Rust library
              shell: devenv shell bash -- -e {0}
              run: |
                  just create-release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
